version: '3'
services:

  github:
    restart: on-failure:10
    build:
      context: ../
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command: ["./wait-for-it.sh","postgres"]
  postgres:
    image: openjdk:11

