on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with docker
        run: docker build . -t name