name: Docker Compose Actions Workflow
on: push
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker up
        run: docker-compose up -d
