name: Spotless formatting test
on:    
  push:    
    branches: [ master ]    
    paths:    
      - 'java/**'    
   pull_request:    
     branches: [ master ]    
     types:    
       - opened    
       - reopened    
       - synchronize    
     paths:    
       - 'java/**'    
   # starring the repo will trigger workflow runs    
   # gives us a way to manually trigger and test the runs    
   watch:    
     types: [ started ]
  jobs:    
    spotless_test:    
      runs-on: ubuntu-latest    
      timeout-minutes: 10
      
      steps:    
        - name: Checkout Repo    
          uses: actions/checkout@v2
          
        - name: Sets up Java    
          uses: actions/setup-java@v1    
          with:    
            java-version: 11
            
        - name: Format java code    
          run: ./java/gradlew -p ./java spotlessApply
    
