# on: push
# name: Main Workflow
# jobs:
#   RunJavaTestCase:
#     name: Run All Java Test Cases
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: Set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#           java-version: '11'
#           distribution: 'adopt'
#     - name: Validate Gradle wrapper
#       uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#     - name: Build with Gradle
#       run: ./test/gradlew -p ./test test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
         - opened
         - reopened
jobs:
  gradle-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      run: ./test/gradlew -p ./test test
